Us1 b
WildCodeSchool/2022-11-JS-RemoteFR-Geekrew-P3-OriginsDigital pull request #30
Opened 2023-03-23 16:05 UTC by fturello

2023-03-23 16:06 UTC, fturello commented
@lchastanet please

2023-03-23 16:07 UTC, Julien879465 approved these changes

2023-03-23 16:07 UTC, antoine-droid approved these changes
🫠

2023-03-23 16:11 UTC, MrRobo1 approved these changes

2023-03-23 16:25 UTC, lchastanet requested changes

2023-03-23 16:25 UTC, lchastanet commented on backend/src/middleware/verifyUser.js
> +  // FavoriteManager.findAllByUserId(req.userId);
Code commented

2023-03-23 16:25 UTC, lchastanet commented on backend/src/router.js
> +// const signUp = require("./controllers/signUpController");
Code commented

2023-03-23 16:25 UTC, lchastanet commented on backend/src/router.js
> +// const verifyUser = require("./middleware/verifyUser");
Code commented

2023-03-23 16:25 UTC, lchastanet commented on backend/src/router.js
> +  // verifyUser,
Code commented

2023-03-23 16:25 UTC, lchastanet commented on frontend/src/components/Footer.jsx
> +/* eslint-disable react/prop-types */
Ah oui carrément

2023-03-23 16:25 UTC, lchastanet commented on frontend/src/pages/Favorites.jsx
> +  // console.log(favorites);
Code commented

2023-03-24 08:39 UTC, fturello commented on backend/src/router.js
> +// const verifyUser = require("./middleware/verifyUser");
i need to keep it for now

2023-03-24 08:39 UTC, fturello commented on backend/src/router.js
> +  // verifyUser,
i need to comment it for now because it breaks my code

2023-03-24 08:44 UTC, lchastanet approved these changes

2023-03-24 08:56 UTC, merged