Us0 navbar add header for home
WildCodeSchool/2022-11-JS-RemoteFR-Geekrew-P3-OriginsDigital pull request #7
Opened 2023-02-23 16:20 UTC by MrRobo1

add header for home page mobile version

2023-02-23 16:24 UTC, lchastanet requested changes

2023-02-23 16:24 UTC, lchastanet commented on package.json
> +    "react-router-dom": "^6.8.1"
it shouldn't be there

2023-02-24 14:11 UTC, MrRobo1 commented on package.json
> +    "react-router-dom": "^6.8.1"
Is it fix

2023-02-24 14:11 UTC, lchastanet approved these changes

2023-02-24 14:12 UTC, fturello approved these changes

2023-02-24 14:12 UTC, antoine-droid approved these changes
Good

2023-02-24 14:13 UTC, merged